/**
 * String → Lucide-icon-component lookup.
 *
 * The trigger and action registries reference icons by name only
 * (a string like `"UserPlus"`). This module imports the Lucide
 * components we use and resolves the name. Unknown names fall
 * back to `Sparkles`.
 *
 * @module app/(dashboard)/automations/[id]/lucide-lookup
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BellRing,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Clock,
  CornerDownLeft,
  CreditCard,
  DoorOpen,
  Eye,
  EyeOff,
  FilePlus2,
  FileSignature,
  FileText,
  FileType2,
  GitBranch,
  Heart,
  Hourglass,
  Instagram,
  Link2,
  ListChecks,
  ListPlus,
  ListX,
  type LucideIcon,
  Mail,
  MailQuestion,
  MessageCircle,
  MessageSquare,
  MoonStar,
  PackageOpen,
  Pause,
  PenTool,
  Pencil,
  Play,
  Receipt,
  Send,
  Settings2,
  Share2,
  Sparkles,
  Square,
  Star,
  StickyNote,
  UserPlus,
  XCircle,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BellRing,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Clock,
  CornerDownLeft,
  CreditCard,
  DoorOpen,
  Eye,
  EyeOff,
  FilePlus2,
  FileSignature,
  FileText,
  FileType2,
  GitBranch,
  Heart,
  Hourglass,
  Instagram,
  Link2,
  ListChecks,
  ListPlus,
  ListX,
  Mail,
  MailQuestion,
  MessageCircle,
  MessageSquare,
  MoonStar,
  PackageOpen,
  Pause,
  Pencil,
  PenTool,
  Play,
  Receipt,
  Send,
  Settings2,
  Share2,
  Sparkles,
  Square,
  Star,
  StickyNote,
  UserPlus,
  XCircle,
}

export function getLucideIcon(name: string | undefined): LucideIcon {
  if (!name) return Sparkles
  return ICONS[name] ?? Sparkles
}
