import type { Profile } from './profile-data';

/**
 * The hand-written profile for Amelia & Jack: booked, fifteen days out,
 * with one loose end. Written to show every part of the profile filled
 * in. Demo data only.
 *
 * @module app/design-system/v2/pages/dashboard/clients/profile/amelia-jack
 */
export const AMELIA_JACK: Profile = {
  event: {
    type: 'Wedding',
    date: 'Sat 10 Oct',
    day: 'Sat 10',
    time: '2:30pm',
    venue: 'Hawthorn Hall',
  },
  today: [
    {
      id: 'numbers',
      label: 'Guest count',
      status: 'Overdue · venue needs it Fri',
      tone: 'danger',
      cta: 'Ask Amelia',
      done: 'Asked Amelia for the guest count',
      draft: {
        channel: 'Email',
        to: 'Amelia',
        subject: 'Final guest numbers for Friday',
        body: 'Hi Amelia,\n\nQuick one: Hawthorn Hall need your final guest numbers by Friday so the caterer can lock in the menu. Could you send them through when you get a sec?\n\nWarmly,\nArjun',
      },
    },
    {
      id: 'timeline',
      label: 'Timeline sign-off',
      status: 'With Jack · unopened 4 days',
      tone: 'warning',
      cta: 'Nudge Jack',
      done: 'Nudged Jack about the timeline',
      draft: {
        channel: 'WhatsApp',
        to: 'Jack',
        body: "Hey Jack! Just checking you've seen the timeline. Photos are now straight after the speeches, like you asked. Could you both give it a quick look and sign off this week?",
      },
    },
  ],
  upcoming: [
    { id: 'invoice', when: 'Tue 29', label: 'Final invoice', zebri: true },
    { id: 'due', when: 'Fri 3', label: '$1,450 due' },
    { id: 'reminder', when: 'Wed 7', label: 'Reminder to both', zebri: true },
    { id: 'rehearsal', when: 'Fri 9', label: 'Rehearsal, 5:00pm' },
  ],
  facts: [
    { label: 'Date', value: 'Sat 10 Oct, 2:30pm' },
    { label: 'Venue', value: 'Hawthorn Hall' },
    { label: 'Rehearsal', value: 'Fri 9 Oct, 5:00pm' },
    { label: 'Guests', value: 'Missing', tone: 'danger' },
    { label: 'Timeline', value: 'v2 · awaiting sign-off', tone: 'warning' },
    { label: 'Package', value: 'Premium · $4,350' },
    { label: 'Paid', value: '$2,900 · $1,450 due 3 Oct' },
    { label: 'Source', value: 'Instagram · Feb' },
  ],
  people: [
    {
      name: 'Amelia Hart',
      role: 'Bride',
      prefers: 'prefers email',
      email: 'amelia.hart@gmail.com',
      phone: '0412 345 678',
    },
    {
      name: 'Jack Moreno',
      role: 'Groom',
      prefers: 'WhatsApp',
      email: 'jack.moreno@outlook.com',
      phone: '0423 456 789',
    },
    {
      name: 'Priya',
      role: 'Venue coordinator',
      prefers: 'phone',
      email: 'priya@hawthornhall.com.au',
      phone: '02 9555 0142',
    },
  ],
  notes: "Margaret (Jack's grandmother, 94) stays seated for the entrance. No garter toss.",
  activity: [
    {
      title: 'This week',
      items: [
        {
          id: 'final-invoice',
          kind: 'zebri',
          who: 'Zebri',
          text: 'scheduled the final invoice',
          sub: 'Sends Tue 29 Sep · $1,450 due Fri 3 Oct',
          time: 'Thu',
          about: 'Automation · Thu',
          title: 'Zebri scheduled the final invoice',
          body: "Invoice #1043 for $1,450 will go to Amelia and Jack on Tue 29 Sep. If it isn't paid by Fri 3 Oct, Zebri sends a gentle reminder.",
          action: 'Edit schedule',
        },
        {
          id: 'second-payment',
          kind: 'payment',
          who: 'Payment',
          text: 'received · $1,450',
          sub: 'Second payment · card ending 4821',
          time: 'Wed',
          about: 'Payment · Wed 24 Sep',
          title: 'Payment received · $1,450',
          body: 'Amelia paid invoice #1038, the second payment, by card ending 4821 through the portal. $1,450 is left to pay, due Fri 3 Oct.',
          action: 'View invoice',
        },
        {
          id: 'timeline-sent',
          kind: 'document',
          who: 'You',
          text: 'sent Timeline v2 to Jack',
          sub: 'Not opened yet',
          time: 'Mon',
          about: 'Document · Mon 22 Sep',
          title: 'You sent Timeline v2 to Jack',
          body: "Sent on WhatsApp and by email. Jack hasn't opened it yet, and it needs his approval before the run sheet is final.",
          action: 'Nudge Jack',
        },
      ],
    },
    {
      title: 'Earlier in September',
      items: [
        {
          id: 'jack-whatsapp',
          kind: 'message',
          who: 'Jack',
          text: 'replied on WhatsApp',
          sub: 'Sounds great, I’ll look at it this weekend.',
          time: '20 Sep',
          about: 'WhatsApp · 20 Sep',
          title: 'Jack replied on WhatsApp',
          body: 'Sounds great, I’ll look at it this weekend.',
          action: 'Reply',
        },
        {
          id: 'amelia-guests',
          kind: 'message',
          who: 'Amelia',
          text: 'replied to “Guest numbers”',
          sub: 'Still waiting on a few RSVPs, will confirm soon.',
          time: '19 Sep',
          lead: true,
          about: 'Email · 19 Sep',
          title: 'Amelia replied to “Guest numbers”',
          body: 'Hi Arjun, still waiting on a few RSVPs, will confirm soon! We’re at 132 so far. Amelia',
          action: 'Reply',
        },
        {
          id: 'questionnaire',
          kind: 'document',
          who: 'Amelia',
          text: 'completed the questionnaire',
          sub: '24 answers · 2 notes flagged',
          time: '2 Sep',
          about: 'Questionnaire · 2 Sep',
          title: 'Amelia completed the questionnaire',
          body: 'All 24 questions answered. Two notes are flagged for you: Margaret stays seated for the entrance, and no garter toss.',
          action: 'Open answers',
        },
      ],
    },
    {
      title: 'March',
      items: [
        {
          id: 'contract',
          kind: 'document',
          who: 'Amelia & Jack',
          text: 'signed the contract',
          sub: 'Premium package · $4,350',
          time: '3 Mar',
          about: 'Contract · 3 Mar',
          title: 'Amelia & Jack signed the contract',
          body: 'Both signed the Premium package agreement for $4,350 on Tue 3 Mar, the same day they paid the deposit.',
          action: 'View contract',
        },
        {
          id: 'deposit',
          kind: 'payment',
          who: 'Payment',
          text: 'received · $1,450',
          sub: 'Deposit',
          time: '3 Mar',
          about: 'Payment · 3 Mar',
          title: 'Payment received · $1,450',
          body: 'Amelia paid the deposit, invoice #1021, by card through the portal. It secured the date.',
          action: 'View invoice',
        },
      ],
    },
    {
      title: 'February',
      items: [
        {
          id: 'intro-call',
          kind: 'call',
          who: 'You',
          text: 'had an intro call',
          sub: '31 min · Sat 10 Oct at Hawthorn Hall, Premium',
          time: '12 Feb',
          about: 'Call · Thu 12 Feb · 31 min',
          title: 'You had an intro call with Amelia & Jack',
          body: 'They found you through Beth’s wedding. Zebri filled in the date, venue and package from the call, and you sent the recap the same night.',
          action: 'Open notes',
        },
      ],
    },
  ],
  glance: [
    { label: 'Last heard from', value: 'Jack · 6 days ago' },
    { label: 'Amelia replies', value: 'In ~2 days, by email' },
    { label: 'Jack replies', value: 'Within the hour' },
    { label: 'Messages', value: '23 in total' },
  ],
  docs: [
    {
      id: 'timeline',
      type: 'PDF',
      title: 'Timeline v2',
      sub: 'Sent to Jack',
      status: 'waiting',
      state: 'Not opened',
      date: '22 Sep',
      group: 'progress',
      facts: [
        { label: 'Sent', value: 'Mon 22 Sep · WhatsApp + email' },
        { label: 'To', value: 'Jack Moreno' },
        { label: 'Opened', value: 'Not yet' },
        { label: 'Needs', value: 'Approval' },
      ],
      action: 'Nudge Jack',
    },
    {
      id: 'final-invoice',
      type: 'INV',
      title: 'Final invoice #1043',
      sub: '$1,450 · due Fri 3 Oct',
      status: 'scheduled',
      state: 'Scheduled',
      date: '29 Sep',
      group: 'progress',
      facts: [
        { label: 'Sends', value: 'Tue 29 Sep, by Zebri' },
        { label: 'To', value: 'Amelia Hart and Jack Moreno' },
        { label: 'Amount', value: '$1,450' },
        { label: 'Due', value: 'Fri 3 Oct' },
      ],
      action: 'Edit schedule',
    },
    {
      id: 'contract',
      type: 'PDF',
      title: 'Contract',
      sub: 'Premium package · $4,350',
      status: 'done',
      state: 'Signed',
      date: '3 Mar',
      group: 'complete',
      facts: [
        { label: 'Signed', value: 'Tue 3 Mar · both' },
        { label: 'Package', value: 'Premium · $4,350' },
      ],
    },
    {
      id: 'questionnaire',
      type: 'FORM',
      title: 'Questionnaire',
      sub: '24 answers',
      status: 'done',
      state: 'Completed',
      date: '2 Sep',
      group: 'complete',
      facts: [
        { label: 'By', value: 'Amelia Hart' },
        { label: 'Answers', value: '24 · 2 notes flagged' },
      ],
      action: 'Open answers',
    },
    {
      id: 'second-payment',
      type: 'INV',
      title: 'Invoice #1038',
      sub: 'Second payment · $1,450',
      status: 'done',
      state: 'Paid',
      date: '24 Sep',
      group: 'complete',
      facts: [
        { label: 'Paid', value: 'Wed 24 Sep · card ending 4821' },
        { label: 'Amount', value: '$1,450' },
      ],
    },
    {
      id: 'deposit',
      type: 'INV',
      title: 'Invoice #1021',
      sub: 'Deposit · $1,450',
      status: 'done',
      state: 'Paid',
      date: '3 Mar',
      group: 'complete',
      facts: [
        { label: 'Paid', value: 'Tue 3 Mar · card' },
        { label: 'Amount', value: '$1,450' },
      ],
    },
    {
      id: 'floor-plan',
      type: 'PDF',
      title: 'Venue floor plan',
      sub: 'From Priya, Hawthorn Hall',
      status: 'received',
      state: 'Received',
      date: '12 Aug',
      group: 'shared',
      facts: [
        { label: 'From', value: 'Priya, Hawthorn Hall' },
        { label: 'Received', value: 'Wed 12 Aug · email' },
      ],
    },
    {
      id: 'seating',
      type: 'XLS',
      title: 'Seating plan draft',
      sub: 'From Amelia',
      status: 'received',
      state: 'Received',
      date: '18 Sep',
      group: 'shared',
      facts: [
        { label: 'From', value: 'Amelia Hart' },
        { label: 'Received', value: 'Fri 18 Sep · portal upload' },
      ],
    },
  ],
};
