/**
 * Proposals feature module: the only import path the rest of the app may use
 * for anything under `features/proposals/`. Everything else in this folder
 * is internal; an ESLint `no-restricted-imports` rule enforces the boundary
 * (see `eslint.config.mjs`, "Feature boundary").
 *
 * Phase 1 exports the layout model, validator, presets, migration and the
 * public renderer. Phase 2 adds the editor state. Later phases add the
 * builder and analytics.
 *
 * @module features/proposals
 */

export type {
  AcceptData, ContentWidth, FaqData, GalleryData, PackagesData, PageSettings, ProposalLayout, RichDoc,
  Section, SectionBackground, SectionData, SectionKind, SectionPadding, SectionStyle, TestimonialsData, VideoData,
} from './model/layout'
export { DATA_TEXT_FIELDS } from './model/layout'
export {
  CONTENT_TEXT_COLOR, CONTENT_WIDTH_PX, detectEmbedProvider, EMBED_PROVIDERS, LAYOUT_LIMITS, MARK_TYPES, NODE_TYPES, SECTION_PADDING_PX,
} from './model/rich-doc-spec'
export type { EmbedProvider, MarkType, NodeType } from './model/rich-doc-spec'
export {
  button, column, columns, doc, docText, embed, heading, hr, image, paragraph, plainText, spacer, text, variable, TABLE_CELL_MIN_WIDTH,
} from './model/doc'
export type { ButtonAction, ButtonAttrs, ImageAttrs, MarkJSON, TableAttrs } from './model/doc'
export { newPackageItem, newPackageOption, PACKAGE_LIMITS, pricedPackage, resolvePackageOptions, starterPackages, toPublicOption } from './model/packages'
export type { PackageItem, PackageOption } from './model/packages'
export { newSectionId, parseProposalLayout, proposalLayoutSchema, proposalThemeSchema } from './model/schema'
export {
  ANIMATION_SPEED_MS, defaultTheme, effectivePadding, effectivePaddingX, effectiveWidth, inheritMatchingDefaults, resolveTheme, SECTION_GAP_PX, SECTION_PADDING_X_PX, THEME_ROLE_FOR, THEME_TEXT_ROLE_LABELS,
  THEME_TEXT_ROLES, themeRoleCss, withTheme,
} from './model/theme'
export type { ProposalTheme, ThemeAnimation, ThemeTextRole, ThemeTextStyle } from './model/theme'
export { layoutFontIds } from './model/layout-fonts'
export { pageSurfaceStyle } from './render/page-surface'
export type { ParseResult } from './model/schema'
export { isProposalVariable, PROPOSAL_VARIABLES, resolveProposalVariables } from './model/variables'
export { isLayoutV2, migrateProposalTreeToLayout, richValueToDoc } from './model/migrate-v1'
export type { MigrateOptions } from './model/migrate-v1'
export { defaultTemplateLayout, PRESET_IDS, PRESET_LABELS, presetSection } from './model/presets'
export type { PresetId } from './model/presets'
export { FIRST_PAGE_ID, splitPages } from './model/pages'
export type { LayoutPage } from './model/pages'
export { KIND_LABELS, sectionLabel } from './model/section-labels'
export { blankTemplateLayout, STARTER_CATEGORIES, TEMPLATE_STARTERS } from './model/starters'
export type { StarterCategory, TemplateStarter } from './model/starters'
export { cloneLayoutWithFreshIds } from './model/clone-layout'
export { embedSrc } from './render/embed-src'
export { HEADING_ROLE, roleCss } from './render/text-roles'
export { RichDocView } from './render/rich-doc'
export { tableColumnWidths, tableLayout } from './render/table-layout'
export type { TableLayout } from './render/table-layout'
export { TableNode } from './render/table-node'
export type { TableNodeProps } from './render/table-node'
export type { RenderMode, RichDocContext } from './render/rich-doc'
export { sectionCss } from './render/section-style'
export { DataSectionView, toV1Block } from './render/data-section'
export type { DataSectionSlots } from './render/data-section'
export { SectionView } from './render/section'
export type { SectionViewProps } from './render/section'
export { ProposalLayoutView } from './render/layout'
export type { ProposalLayoutViewProps } from './render/layout'
export { LayoutThumbnail, layoutIsBlank } from './render/layout-thumbnail'
export type { LayoutThumbnailProps } from './render/layout-thumbnail'
export {
  createTemplateAction, deleteTemplateAction, duplicateTemplateAction, ensureDefaultTemplateAction, getTemplateAction,
  listTemplatesAction, renameTemplateAction, setDefaultTemplateAction, updateTemplateLayoutAction, updateTemplateSettingsAction,
} from './data/templates'
export type { SaveLayoutResult, TemplateListItem, TemplateRecord, TemplateSummary } from './data/templates'
export { updateTemplateLayoutSchema } from './data/template-schemas'
export { getProposalSettingsAction, updateProposalSettingsAction } from './data/settings'
export type { ProposalSettings } from './data/settings'
export type { ProposalSettingsSnapshot, UpdateProposalSettingsInput, UpdateTemplateSettingsInput } from './data/settings-schemas'
export { resolveTemplateSettings } from './data/settings-schemas'
export { applyThemePatch, layoutReducer, newSectionFor } from './editor/state'
export { GlobalStylePopover } from './editor/global-style/global-style-popover'
export type { GlobalStylePopoverProps } from './editor/global-style/global-style-popover'
export type { LayoutAction, LayoutEditorState, NodeSelection, Selection, ThemePatch } from './editor/state'
export { useLayoutEditor } from './editor/use-layout-editor'
export type { UseLayoutEditorReturn } from './editor/use-layout-editor'
export {
  buildRichDocExtensions, EDITOR_MARK_NAMES, EDITOR_NODE_NAMES, filterProposalVariables, InlineFieldSlashVariableExtension, normaliseEditorJSON,
  SLASH_MENU_PLUGIN_KEY, SlashMenuExtension, VARIABLE_AT_PLUGIN_KEY, VARIABLE_BRACES_PLUGIN_KEY, VARIABLE_SLASH_PLUGIN_KEY, VariableSuggestionExtension,
} from './editor/extensions'
export type { RichDocExtensionOptions } from './editor/extensions'
export { CONTENT_PLACEHOLDER, ContentSectionEditor } from './editor/content-section-editor'
export type { ContentSectionEditorProps, EditorNodeSelection } from './editor/content-section-editor'
export {
  getEditor, getRegisteredEditors, registerEditor, unregisterEditor, useRegisteredEditor, useRegisteredEditors,
} from './editor/editor-registry'
export { LinkHoverTooltip } from './editor/link-hover-tooltip'
export { EDITOR_PROSE_CLASS } from './editor/editor-styles'
export { InlineField } from './editor/data/inline-field'
export { FieldShortcutsProvider, useFieldShortcuts } from './editor/data/field-shortcuts'
export type { FieldShortcuts } from './editor/data/field-shortcuts'
export type { InlineFieldProps } from './editor/data/inline-field'
export { EditableDataSection } from './editor/data/editable-data-section'
export type { EditableDataSectionProps } from './editor/data/editable-data-section'
export type { EditSlotArgs } from './editor/data/edit-slot-args'
export { AddFaqItem, faqSlots } from './editor/data/edit-faq'
export type { AddFaqItemProps } from './editor/data/edit-faq'
export { AddTestimonialItem, testimonialsSlots } from './editor/data/edit-testimonials'
export type { AddTestimonialItemProps } from './editor/data/edit-testimonials'
export { acceptSlots } from './editor/data/edit-accept'
export { AddPackageTile, packagesSlots } from './editor/data/edit-packages'
export type { AddPackageTileProps } from './editor/data/edit-packages'
export { packageCardSlots } from './editor/data/edit-package-card'
export { setPackageOptions } from './editor/data/package-args'
export type { PackageCardArgs } from './editor/data/package-args'
export { PackageCardMenu } from './editor/data/package-card-menu'
export type { PackageCardMenuProps } from './editor/data/package-card-menu'
export { InlineNumber } from './editor/data/inline-number'
export type { InlineNumberProps } from './editor/data/inline-number'
export { ToolbarPopover } from './editor/bars/toolbar-popover'
export type { ToolbarPopoverProps } from './editor/bars/toolbar-popover'
export { AcceptButtonPopover } from './editor/data/accept-button-popover'
export type { AcceptButtonPopoverProps } from './editor/data/accept-button-popover'
export { LabelWithVariables } from './editor/data/label-with-variables'
export type { LabelWithVariablesProps } from './editor/data/label-with-variables'
export { AddPhotosTile, gallerySlots } from './editor/data/edit-gallery'
export type { AddPhotosTileProps } from './editor/data/edit-gallery'
export { videoSlots } from './editor/data/edit-video'
export { VideoSourceModal, VIDEO_URL_ERROR } from './editor/data/video-source-modal'
export type { VideoSourceModalProps } from './editor/data/video-source-modal'
export { PackagesButtonPopover } from './editor/data/packages-button-popover'
export type { PackagesButtonPopoverProps } from './editor/data/packages-button-popover'
export { PackagesPricePopover } from './editor/data/packages-price-popover'
export type { PackagesPricePopoverProps } from './editor/data/packages-price-popover'
export { TestimonialPhoto } from './editor/data/testimonial-photo'
export type { TestimonialPhotoProps } from './editor/data/testimonial-photo'
export { useMediaUpload } from './editor/data/use-media-upload'
export type { UseMediaUploadResult } from './editor/data/use-media-upload'
export { SectionCanvas } from './editor/section-canvas'
export type { SectionCanvasProps } from './editor/section-canvas'
export { EditableSection } from './editor/editable-section'
export type { EditableSectionProps } from './editor/editable-section'
export { PageSheet } from './editor/page-sheet'
export type { PageSheetProps } from './editor/page-sheet'
export {
  FULL_HEIGHT_THRESHOLD_PX, PADDING_SNAPS, paddingToPx, pxToPadding, pxToWidth, widthToPx, WIDTH_SNAPS,
} from './editor/resize/section-resize-math'
export { SectionHeightGrip } from './editor/resize/section-height-grip'
export type { SectionHeightGripProps } from './editor/resize/section-height-grip'
export { SectionWidthHandles } from './editor/resize/section-width-handles'
export type { ColumnRect, SectionWidthHandlesProps } from './editor/resize/section-width-handles'
export { GalleryHeightHandle } from './editor/resize/gallery-height-handle'
export type { GalleryHeightHandleProps } from './editor/resize/gallery-height-handle'
export { SectionResizeOverlay } from './editor/resize/section-resize-overlay'
export type { SectionResizeOverlayProps } from './editor/resize/section-resize-overlay'
export { isSectionEmpty, useCanvasKeys, useDeleteSection } from './editor/use-canvas-keys'
export type { UseCanvasKeysOptions, UseDeleteSectionReturn } from './editor/use-canvas-keys'
export { stepSelectionOut } from './editor/step-selection-out'
export type { StepSelectionOutOptions } from './editor/step-selection-out'
export { useEditorShortcuts } from './editor/use-editor-shortcuts'
export type { UseEditorShortcutsOptions } from './editor/use-editor-shortcuts'
export { InsertMediaHost } from './editor/insert-media-host'
export type { InsertMediaHandle, InsertMediaHostProps } from './editor/insert-media-host'
export { useInsertMedia } from './editor/use-insert-media'
export type { UseInsertMediaOptions } from './editor/use-insert-media'
export { insertAtomNode } from './editor/insert-atom-node'
export { EmbedInsertModal } from './editor/embed-insert-modal'
export type { EmbedInsertModalProps } from './editor/embed-insert-modal'
export { InsertMediaStatusPill } from './editor/insert-media-status-pill'
export type { InsertMediaStatus, InsertMediaStatusPillProps } from './editor/insert-media-status-pill'
export { AddLine, SECTION_CAP_MESSAGE } from './editor/add-line'
export type { AddLineProps } from './editor/add-line'
export { AddPalette } from './editor/add-palette'
export type { AddPaletteProps } from './editor/add-palette'
export { PaletteBody } from './editor/palette-body'
export type { PaletteBodyProps } from './editor/palette-body'
export { TabButton } from './editor/tab-button'
export type { TabButtonProps } from './editor/tab-button'
export { useAddPalette } from './editor/use-add-palette'
export type { UseAddPaletteReturn } from './editor/use-add-palette'
export { filterInsertItems, INSERT_ITEMS } from './editor/insert-items'
export type { InsertGroup, InsertItem } from './editor/insert-items'
export { EditorCanvasRegion } from './editor/editor-canvas-region'
export type { EditorCanvasRegionProps } from './editor/editor-canvas-region'
export { ImageInsertModal, PROPOSAL_IMAGES_QUERY_KEY } from './editor/image-insert-modal'
export type { ImageInsertModalProps } from './editor/image-insert-modal'
export { LibraryImageGrid } from './editor/library/library-image-grid'
export type { LibraryImageGridProps } from './editor/library/library-image-grid'
export { LibraryItemCard, LIBRARY_CAP_MESSAGE } from './editor/library/library-item-card'
export type { LibraryItemCardProps } from './editor/library/library-item-card'
export { presetLibraryEntries, sectionLibraryEntries, SECTION_ITEMS } from './editor/library/library-items'
export type { LibraryEntry } from './editor/library/library-items'
export { listProposalImages, MEDIA_LIMITS, uploadProposalMediaFile } from './data/media'
export type { MediaKind, MediaLimit, ProposalImage } from './data/media'
export { BarShell } from './editor/bars/bar-shell'
export type { BarShellProps } from './editor/bars/bar-shell'
export { ControlDot, OverrideDot } from './editor/bars/override-dot'
export type { ControlDotProps, OverrideDotProps } from './editor/bars/override-dot'
export { SectionToolbar } from './editor/bars/section-toolbar'
export type { SectionToolbarProps } from './editor/bars/section-toolbar'
export { SectionStylePopover } from './editor/bars/section-style-popover'
export type { SectionStylePopoverProps } from './editor/bars/section-style-popover'
export { LINK_ERROR, LINK_PATTERN } from './editor/bars/link-popover'
export { applyTextStyle, bubbleShouldShow, readTextState } from './editor/bars/text-bar-style'
export type { CaseValue, StyleValue, TextState, TextStylePatch } from './editor/bars/text-bar-style'
export { TextBar, TextBarRow } from './editor/bars/text-bar'
export type { TextBarHandle, TextBarProps } from './editor/bars/text-bar'
export { NodeBar } from './editor/bars/node-bar'
export type { NodeBarProps } from './editor/bars/node-bar'
export { NodeBarAnchor } from './editor/bars/node-bar-anchor'
export type { NodeBarAnchorProps } from './editor/bars/node-bar-anchor'
export { useNodeBarContent } from './editor/bars/use-node-bar-content'
export type { UseNodeBarContentOptions, UseNodeBarContentReturn } from './editor/bars/use-node-bar-content'
export type { NodeBarSection } from './editor/bars/node-bar-shared'
export { EMBED_ERROR } from './editor/bars/node-bar-embed'
export { ALT_WARNING } from './editor/bars/node-bar-image'
export { PreviewOverlay } from './editor/preview-overlay'
export type { PreviewOverlayProps } from './editor/preview-overlay'
export { usePreviewShortcut } from './editor/use-preview-shortcut'
export { TemplateEditor } from './editor/template-editor'
export type { TemplateEditorProps } from './editor/template-editor'
export { useTemplateAutosave } from './editor/use-template-autosave'
export type { UseTemplateAutosaveOptions, UseTemplateAutosaveReturn } from './editor/use-template-autosave'
export { clearDraft, draftKey, readDraft, reconcileDraft, writeDraft } from './editor/local-draft'
export type { LocalDraft, ReconciledLayout } from './editor/local-draft'
export { useRehydrateEditor } from './editor/use-rehydrate-editor'
