-- Reseed every seeded user's starter email templates with the cleaned set.
--
-- The canonical library (lib/email/starter-templates.ts) was edited to
-- remove em-dashes and fix null-prone greetings (e.g. "Hi {{primary_name}}
-- and {{spouse_name}}," -> "Hi {{couple.name}},"). Seeding is idempotent
-- (only fires for users with zero templates), so existing libraries kept
-- the stale copies. This backfill replaces them.
--
-- Decision (2026-06-18, user-approved): WIPE & REPLACE all is_starter
-- templates for every user who currently has any — user edits to starter
-- rows are intentionally discarded. User-created (is_starter = false)
-- templates are never touched.
--
-- Atomic: a single statement. The seeded_users CTE captures the user set
-- on the pre-delete snapshot, the deleted CTE removes the old starters,
-- and the INSERT re-seeds from that captured set. Re-running is safe
-- (it just rewrites the same rows).
--
-- @ALLOW_DESTRUCTIVE: replace is_starter email_templates for all seeded users (user-approved)

with seeded_users as (
  select distinct user_id from public.email_templates where is_starter = true
),
deleted as (
  delete from public.email_templates where is_starter = true returning 1
)
insert into public.email_templates
  (user_id, name, description, subject, content, lifecycle_stage, is_starter, position)
select
  su.user_id, t.name, t.description, t.subject, t.content::jsonb, t.lifecycle_stage, true, t.position
from seeded_users su
cross join (
  values
    ($tpl$Enquiry acknowledgement$tpl$, $tpl$Thank a couple for their enquiry and set expectations.$tpl$, $tpl$Thanks for reaching out, {{couple.primary_name}}$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you so much for getting in touch about your wedding! I would love to hear more about your day and how I can help."}]},{"type":"paragraph","content":[{"type":"text","text":"Could you share your event date, venue, and a little about what you have in mind? I will get back to you with availability and next steps."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$enquiry$tpl$, 0),
    ($tpl$Availability: yes$tpl$, $tpl$Confirm you are available for the couple’s date.$tpl$, $tpl$Good news: I’m available for your wedding$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Wonderful news: I am available on "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":" and would be delighted to be part of your day."}]},{"type":"paragraph","content":[{"type":"text","text":"I will put together a quote for you shortly. In the meantime, feel free to reply with any questions."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$enquiry$tpl$, 10),
    ($tpl$Booked out: referral$tpl$, $tpl$Politely decline when you are unavailable and offer to refer.$tpl$, $tpl$About your wedding date$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you for thinking of me! Unfortunately I am already booked on "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":", so I am not able to take on your wedding."}]},{"type":"paragraph","content":[{"type":"text","text":"I would hate to leave you without options, so if it would help, I am happy to refer you to a trusted colleague. Just let me know."}]},{"type":"paragraph","content":[{"type":"text","text":"Wishing you a wonderful celebration,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]}]}$tpl$, $tpl$enquiry$tpl$, 20),
    ($tpl$Discovery call invite$tpl$, $tpl$Invite the couple to a quick call to talk through their day.$tpl$, $tpl$Let’s have a quick chat about your day$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"The best way to see if we are a great fit is a quick, no-pressure chat. I would love to learn about you both and your plans for the day."}]},{"type":"paragraph","content":[{"type":"text","text":"Reply with a couple of times that suit you and I will lock one in."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$enquiry$tpl$, 30),
    ($tpl$Quote cover email$tpl$, $tpl$Send the couple their quote with a warm note.$tpl$, $tpl$Your quote from {{mc.business_name}}$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you for the opportunity. I have put together a quote for your wedding on "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"You can view it here: "},{"type":"mention","attrs":{"id":"quote.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Let me know if you have any questions or would like to tweak anything. I am happy to help."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$quote$tpl$, 40),
    ($tpl$Quote follow-up nudge$tpl$, $tpl$Gently follow up on a quote you have not heard back on.$tpl$, $tpl$Just checking in on your quote$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"I wanted to gently check in on the quote I sent through. No rush at all, I know wedding planning keeps you busy!"}]},{"type":"paragraph","content":[{"type":"text","text":"You can revisit it any time here: "},{"type":"mention","attrs":{"id":"quote.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"If anything needs adjusting, just say the word."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$quote$tpl$, 50),
    ($tpl$Quote expiring soon$tpl$, $tpl$Let the couple know their quote is about to expire.$tpl$, $tpl$Your quote expires soon$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"A quick heads-up that your quote is due to expire shortly. I would love to keep your date held for you."}]},{"type":"paragraph","content":[{"type":"text","text":"You can review and accept it here: "},{"type":"mention","attrs":{"id":"quote.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Happy to answer any last questions before you decide."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$quote$tpl$, 60),
    ($tpl$You’re booked: confirmation$tpl$, $tpl$Celebrate the booking and outline next steps.$tpl$, $tpl$You’re booked! 🎉$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"It is official! I am honoured to be part of your wedding on "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":" at "},{"type":"mention","attrs":{"id":"venue.name"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"I will be in touch with the next steps shortly, including your agreement and planning details. For now, congratulations and thank you for trusting me with your day."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$booking$tpl$, 70),
    ($tpl$Agreement to sign$tpl$, $tpl$Send the contract for signature.$tpl$, $tpl$Your agreement is ready to sign$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"To lock everything in, here is your agreement to review and sign: "},{"type":"mention","attrs":{"id":"contract.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Once that is signed we are all set. Let me know if anything is unclear and I am happy to walk you through it."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$booking$tpl$, 80),
    ($tpl$Deposit invoice$tpl$, $tpl$Request the deposit to secure the date.$tpl$, $tpl$Deposit invoice to secure your date$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Here is your deposit invoice to secure "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":": "},{"type":"mention","attrs":{"id":"invoice.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Once the deposit is received your booking is confirmed. Thank you!"}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$booking$tpl$, 90),
    ($tpl$Payment received: thank you$tpl$, $tpl$Acknowledge a received payment.$tpl$, $tpl$Payment received, thank you$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you! Your payment has come through and everything is up to date. I truly appreciate it."}]},{"type":"paragraph","content":[{"type":"text","text":"I am looking forward to working with you towards your big day."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$booking$tpl$, 100),
    ($tpl$Planning questionnaire request$tpl$, $tpl$Ask the couple to complete their planning details.$tpl$, $tpl$Let’s start planning your ceremony$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"It is time for the fun part: planning your day! Please complete your planning details in your portal here: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"This helps me tailor everything to you. There are no wrong answers, and you can save and return any time."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 110),
    ($tpl$Song & music requests$tpl$, $tpl$Collect the couple’s music choices.$tpl$, $tpl$Your music & song choices$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Music sets the mood for your day. When you have a moment, please add your song choices in your portal: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Think processional, signing, and recessional, plus any special songs that mean something to you both."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 120),
    ($tpl$Run sheet draft for review$tpl$, $tpl$Share the draft timeline for the couple to review.$tpl$, $tpl$Your draft run sheet to review$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"I have put together a draft run sheet for your day. Please take a look in your portal and let me know if anything needs adjusting: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Once you are happy, I will finalise it and share with your vendors."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 130),
    ($tpl$Final details confirmation$tpl$, $tpl$Confirm key logistics about two weeks out.$tpl$, $tpl$Confirming the final details for your day$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"We are getting close! With "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":" nearly here, I would love to confirm the final details for "},{"type":"mention","attrs":{"id":"venue.name"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Please review everything in your portal and flag any last changes: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 140),
    ($tpl$Final balance reminder$tpl$, $tpl$Remind the couple of the remaining balance.$tpl$, $tpl$A friendly reminder about your final balance$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Just a gentle reminder that your final balance is due ahead of the big day. You can settle it here: "},{"type":"mention","attrs":{"id":"invoice.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you so much, almost there!"}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 150),
    ($tpl$NOIM request (celebrant)$tpl$, $tpl$Request the couple lodge the Notice of Intended Marriage.$tpl$, $tpl$Your Notice of Intended Marriage (NOIM)$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Under Australian marriage law, your Notice of Intended Marriage (NOIM) must be completed and lodged with me at least one month before your ceremony (and no more than 18 months prior)."}]},{"type":"paragraph","content":[{"type":"text","text":"Please complete and return your NOIM at your earliest convenience so we stay comfortably within the legal timeframe. I will guide you through every step."}]},{"type":"paragraph","content":[{"type":"text","text":"If you have any questions about the form, just ask. This is my area."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 160),
    ($tpl$Required documents request (celebrant)$tpl$, $tpl$Request the legal identity documents you must sight.$tpl$, $tpl$Documents I’ll need to see before your ceremony$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"To meet my legal obligations as your celebrant, I need to sight a few documents for each of you before the ceremony:"}]},{"type":"paragraph","content":[{"type":"text","text":"• Proof of date and place of birth (birth certificate or passport)"}]},{"type":"paragraph","content":[{"type":"text","text":"• Photo identification (driver licence or passport)"}]},{"type":"paragraph","content":[{"type":"text","text":"• If either of you has been married before: divorce decree absolute or the death certificate of a former spouse"}]},{"type":"paragraph","content":[{"type":"text","text":"You can upload these securely in your portal: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 170),
    ($tpl$Ceremony script for review (celebrant)$tpl$, $tpl$Share the draft ceremony script for the couple’s feedback.$tpl$, $tpl$Your draft ceremony script$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"I have drafted your ceremony script and would love your thoughts. It includes the legal wording required by the Marriage Act alongside the personal touches we discussed."}]},{"type":"paragraph","content":[{"type":"text","text":"You can review it in your portal here: "},{"type":"mention","attrs":{"id":"portal.link"}}]},{"type":"paragraph","content":[{"type":"text","text":"Take your time. This is your story, and I want it to feel just right."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$planning$tpl$, 180),
    ($tpl$Marriage certificate info (celebrant)$tpl$, $tpl$Explain certificates and registration after the wedding.$tpl$, $tpl$About your marriage certificate$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Congratulations again! Now for the paperwork side: I will register your marriage with the relevant Births, Deaths and Marriages registry within the legal timeframe."}]},{"type":"paragraph","content":[{"type":"text","text":"On the day you will receive a ceremonial certificate. If you would like an official standard marriage certificate (often needed for name changes), you can apply through your state or territory registry, and I am happy to point you to the right place."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$follow_up$tpl$, 190),
    ($tpl$Day-of logistics: see you soon$tpl$, $tpl$A warm note in the final days before the wedding.$tpl$, $tpl$See you very soon!$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"The big day is almost here! I will arrive ahead of time on "},{"type":"mention","attrs":{"id":"event.weekday"}},{"type":"text","text":" at "},{"type":"mention","attrs":{"id":"venue.name"}},{"type":"text","text":" so everything runs smoothly."}]},{"type":"paragraph","content":[{"type":"text","text":"Try to relax and soak it all in. You are in good hands, and I cannot wait to celebrate with you."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$wedding_week$tpl$, 200),
    ($tpl$Final run sheet to vendors$tpl$, $tpl$Share the finalised run sheet with the couple and vendors.$tpl$, $tpl$Final run sheet for {{couple.name}}’s wedding$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi everyone,"}]},{"type":"paragraph","content":[{"type":"text","text":"Please find the final run sheet for "},{"type":"mention","attrs":{"id":"couple.name"}},{"type":"text","text":"’s wedding on "},{"type":"mention","attrs":{"id":"event.date | friendly"}},{"type":"text","text":" at "},{"type":"mention","attrs":{"id":"venue.name"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Let me know if anything looks off on your end. Looking forward to a wonderful day together."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$wedding_week$tpl$, 210),
    ($tpl$Thank you & congratulations$tpl$, $tpl$A heartfelt thank-you after the wedding.$tpl$, $tpl$Thank you, what a day!$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"What an absolute joy it was to be part of your wedding. Thank you for trusting me with such a special role; I loved every moment."}]},{"type":"paragraph","content":[{"type":"text","text":"Wishing you both a lifetime of happiness."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$follow_up$tpl$, 220),
    ($tpl$Review request$tpl$, $tpl$Invite the couple to leave a review.$tpl$, $tpl$Would you share a few words?$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"I hope you are still floating on cloud nine! If you have a spare moment, a short review would mean the world and helps other couples find me."}]},{"type":"paragraph","content":[{"type":"text","text":"No pressure at all, only if you feel like it. Thank you again for having me."}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$follow_up$tpl$, 230),
    ($tpl$Referral request$tpl$, $tpl$Ask happy couples to refer friends.$tpl$, $tpl$Know someone getting married?$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.primary_name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"If any of your friends or family are planning their wedding, I would be honoured if you pointed them my way. There is no greater compliment than a referral from a couple I have worked with."}]},{"type":"paragraph","content":[{"type":"text","text":"Thank you, and congratulations once more!"}]},{"type":"paragraph","content":[{"type":"text","text":"Warm regards,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.business_name"}}]}]}$tpl$, $tpl$follow_up$tpl$, 240),
    ($tpl$Anniversary message$tpl$, $tpl$A warm note around the couple’s first anniversary.$tpl$, $tpl$Happy anniversary!$tpl$, $tpl${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hi "},{"type":"mention","attrs":{"id":"couple.name"}},{"type":"text","text":","}]},{"type":"paragraph","content":[{"type":"text","text":"Happy anniversary! I was thinking of you both and the beautiful day we shared. I hope this year has been everything you dreamed of."}]},{"type":"paragraph","content":[{"type":"text","text":"Sending you my very best,"}]},{"type":"paragraph","content":[{"type":"mention","attrs":{"id":"mc.contact_name"}}]}]}$tpl$, $tpl$follow_up$tpl$, 250)
) as t(name, description, subject, content, lifecycle_stage, position);
